### ISSUE TITLE
Bug: clicking on gotoClass URL when current view is /myclasses/ creates some sort of route endless loop

### ISSUE THREAD

**Issue by andrelandgraf** [tum-aweink/high5-learning-frontend#23] opened 2018-06-02 07:48 UTC
Registering to a class (as a student) works fine, clicking on the gotoclass url link directly from myclasses creates an endless loop of redirecting to each other. 

I think this is because we are already member of the class, so we get redirected to myclasses somehow.

**Comment by andreweinkoetz** [comment] 2018-06-02 13:56
This is caused by this piece of code in ClassListView:

```
const lastPath = String(document.referrer).substring("http://localhost:3000/".length);

        if ((lastPath.substring(0,"goToClass".length)) === "goToClass") {
            window.location = document.referrer;
        };
```

Do we need this? @HmG248

**Comment by HmG248** [comment] 2018-06-03 06:50
I will fix this today, this code is needed so that a user which is not registered/logged in and clicks on the link will be redirected to goToClass after registering/logging in

**Comment by HmG248** [comment] 2018-06-04 16:11
Consider this bug fixed by deleting the lines you snapshoted

**Closed as completed by HmG248** 2018-06-04 16:11 UTC
Labels: bug
